import { Router } from 'express';
import * as ctrl from '../controllers/developer.controller';
const router = Router();
router.get('/api-keys', (ctrl as any).getApiKeys);
router.post('/api-keys', (ctrl as any).createApiKey);
router.delete('/api-keys/:id', (ctrl as any).deleteApiKey);
router.get('/webhooks', (ctrl as any).getWebhooks);
router.post('/webhooks', (ctrl as any).createWebhook);
router.delete('/webhooks/:id', (ctrl as any).deleteWebhook);
export default router;
