import { Response } from 'express';
import prisma from '../../../core/prisma';
import { ControlPlaneRequest } from '../middleware/control-plane-auth.middleware';
import { writeControlPlaneAudit } from '../services/control-plane-audit.service';

const STEP_STATUSES=new Set(['PENDING','IN_PROGRESS','COMPLETED','BLOCKED','SKIPPED']);
const ASSET_KINDS=new Set(['LEGAL_ENTITY','COMPANY_NUMBER','BANK_ACCOUNT','ACQUIRER','DOMAIN','EMAIL','PHONE','VPS','WEBSITE','XPAYMENTS_STORE','GATEWAY_VAULT','PROVIDER_CONNECTION','DOCUMENT','OTHER']);
const text=(v:unknown,max=4000)=>String(v??'').trim().slice(0,max);
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
async function cpAudit(req:ControlPlaneRequest,action:string,id:string,before?:unknown,after?:unknown,metadata?:Record<string,unknown>){await writeControlPlaneAudit({actorUserId:req.controlPlane?.userId||null,action,entityType:'service_order',entityId:id,beforeData:before,afterData:after,metadata,req});}
async function recalc(orderId:string){const steps=await prisma.$queryRawUnsafe<any[]>(`select code,status,position from service_order_steps where service_order_id=$1::uuid order by position`,orderId);const total=steps.length||1,completed=steps.filter(s=>['COMPLETED','SKIPPED'].includes(String(s.status))).length,active=steps.find(s=>String(s.status)==='IN_PROGRESS'),pos=active?Number(active.position):completed,progress=completed===total?100:Math.max(5,Math.min(99,Math.round(Math.max(completed,pos)/total*100))),status=completed===total?'DELIVERED':(active?.code||'IN_PROGRESS');await prisma.$executeRawUnsafe(`update service_orders set progress=$2,status=$3,updated_at=now() where id=$1::uuid`,orderId,progress,status);return{progress,status};}

export async function getExpertOrderDetail(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80);const order=(await prisma.$queryRawUnsafe<any[]>(`select so.*,m.name merchant_name,m.email merchant_email,o.code offering_code,o.name offering_name,o.jurisdiction from service_orders so join merchants m on m.id=so.merchant_id join service_offerings o on o.id=so.offering_id where so.id=$1::uuid`,id))[0];if(!order)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Contratação não encontrada.'}});const [steps,assets,requirements,documents,proofs,tickets]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`select * from service_order_steps where service_order_id=$1::uuid order by position`,id),prisma.$queryRawUnsafe<any[]>(`select * from service_order_assets where service_order_id=$1::uuid order by created_at`,id),prisma.$queryRawUnsafe<any[]>(`select * from service_order_requirements where service_order_id=$1::uuid order by created_at`,id),prisma.$queryRawUnsafe<any[]>(`select id,kind,label,status,file_name,mime_type,file_size,created_at,updated_at from service_order_documents where service_order_id=$1::uuid order by created_at`,id),prisma.$queryRawUnsafe<any[]>(`select id,status,channel,reference,note,created_at,updated_at from service_order_payment_proofs where service_order_id=$1::uuid order by created_at`,id),prisma.$queryRawUnsafe<any[]>(`select id,ticket_code,subject,status,priority,updated_at from support_tickets where service_order_id=$1::uuid order by updated_at desc`,id)]);return res.json({success:true,data:{order,steps,assets,requirements,documents,paymentProofs:proofs,tickets}});}catch(e:any){console.error('[cp.expert.detail]',e);return res.status(500).json({success:false,error:{code:'READ_ERROR',message:'Falha ao carregar contratação.'}});}}

export async function updateExpertOrder(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80);const before=(await prisma.$queryRawUnsafe<any[]>(`select id,status,progress,payment_status,assigned_to,internal_notes,customer_notes,target_store_id,metadata from service_orders where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Contratação não encontrada.'}});let target=req.body?.targetStoreId===undefined?before.target_store_id:(text(req.body.targetStoreId,80)||null);if(target){const s=(await prisma.$queryRawUnsafe<any[]>(`select id,merchant_id from stores where id=$1::uuid`,target))[0];const owner=(await prisma.$queryRawUnsafe<any[]>(`select merchant_id from service_orders where id=$1::uuid`,id))[0];if(!s||String(s.merchant_id)!==String(owner.merchant_id))return res.status(409).json({success:false,error:{code:'TARGET_STORE_MISMATCH',message:'Target Store não pertence ao Merchant da contratação.'}});}const rows=await prisma.$queryRawUnsafe<any[]>(`update service_orders set assigned_to=$2,internal_notes=$3,customer_notes=$4,target_store_id=$5::uuid,metadata=$6::jsonb,updated_at=now() where id=$1::uuid returning *`,id,req.body?.assignedTo===undefined?before.assigned_to:(text(req.body.assignedTo,250)||null),req.body?.internalNotes===undefined?before.internal_notes:(text(req.body.internalNotes,12000)||null),req.body?.customerNotes===undefined?before.customer_notes:(text(req.body.customerNotes,12000)||null),target,JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):obj(req.body.metadata)));await cpAudit(req,'EXPERT_ORDER_UPDATED',id,before,rows[0]);return res.json({success:true,data:{order:rows[0]}});}catch(e:any){console.error('[cp.expert.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar contratação.'}});}}

export async function updateExpertStep(req:ControlPlaneRequest,res:Response){try{const orderId=text(req.params.id,80),code=text(req.params.stepCode,100).toUpperCase(),status=text(req.body?.status,50).toUpperCase(),notes=text(req.body?.notes,4000)||null;if(!STEP_STATUSES.has(status))return res.status(400).json({success:false,error:{code:'BAD_STATUS',message:'Estado da etapa inválido.'}});const before=(await prisma.$queryRawUnsafe<any[]>(`select * from service_order_steps where service_order_id=$1::uuid and code=$2 limit 1`,orderId,code))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Etapa não encontrada.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update service_order_steps set status=$3,notes=$4,started_at=case when $3='IN_PROGRESS' then coalesce(started_at,now()) else started_at end,completed_at=case when $3 in ('COMPLETED','SKIPPED') then coalesce(completed_at,now()) else null end,updated_at=now() where service_order_id=$1::uuid and code=$2 returning *`,orderId,code,status,notes);const calc=await recalc(orderId);await cpAudit(req,'EXPERT_STEP_UPDATED',orderId,before,rows[0],{stepCode:code,...calc});return res.json({success:true,data:{step:rows[0],order:calc}});}catch(e:any){console.error('[cp.expert.step]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar etapa.'}});}}

export async function createExpertAsset(req:ControlPlaneRequest,res:Response){try{const orderId=text(req.params.id,80),kind=text(req.body?.kind,80).toUpperCase(),label=text(req.body?.label,250)||null,value=text(req.body?.valueText,4000)||null,url=text(req.body?.url,2000)||null;if(!ASSET_KINDS.has(kind)||(!value&&!url))return res.status(400).json({success:false,error:{code:'BAD_ASSET',message:'Kind válido e valueText/url são obrigatórios.'}});const exists=await prisma.$queryRawUnsafe<any[]>(`select id from service_orders where id=$1::uuid`,orderId);if(!exists[0])return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Contratação não encontrada.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`insert into service_order_assets(service_order_id,kind,label,value_text,url,sensitive,metadata) values($1::uuid,$2,$3,$4,$5,$6,$7::jsonb) returning *`,orderId,kind,label,value,url,req.body?.sensitive===true,JSON.stringify(obj(req.body?.metadata)));await cpAudit(req,'EXPERT_ASSET_CREATED',orderId,undefined,{...rows[0],value_text:req.body?.sensitive===true?'[REDACTED]':rows[0].value_text});return res.status(201).json({success:true,data:{asset:rows[0]}});}catch(e:any){console.error('[cp.expert.asset]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar asset.'}});}}

export async function deleteExpertAsset(req:ControlPlaneRequest,res:Response){try{const orderId=text(req.params.id,80),assetId=text(req.params.assetId,80);const before=(await prisma.$queryRawUnsafe<any[]>(`select * from service_order_assets where id=$1::uuid and service_order_id=$2::uuid`,assetId,orderId))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Asset não encontrado.'}});await prisma.$executeRawUnsafe(`delete from service_order_assets where id=$1::uuid and service_order_id=$2::uuid`,assetId,orderId);await cpAudit(req,'EXPERT_ASSET_DELETED',orderId,{...before,value_text:before.sensitive?'[REDACTED]':before.value_text},undefined,{assetId});return res.json({success:true,data:{deleted:true,assetId}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar asset.'}});}}

export async function confirmExpertPayment(req:ControlPlaneRequest,res:Response){try{const orderId=text(req.params.id,80),proofReference=text(req.body?.proofReference,300)||null,note=text(req.body?.note,2000)||null,actor=req.controlPlane!;const result=await prisma.$transaction(async tx=>{const before=(await tx.$queryRawUnsafe<any[]>(`select id,payment_status,status,progress,metadata from service_orders where id=$1::uuid for update`,orderId))[0];if(!before)throw new Error('NOT_FOUND');if(before.payment_status==='PAID')return{already:true,before,after:before};const metadata={...(before.metadata||{}),manualPaymentConfirmation:{confirmedAt:new Date().toISOString(),confirmedByControlPlane:actor.userId,proofReference,note}};await tx.$executeRawUnsafe(`update service_orders set payment_status='PAID',metadata=$2::jsonb,updated_at=now() where id=$1::uuid`,orderId,JSON.stringify(metadata));await tx.$executeRawUnsafe(`update service_order_steps set status='COMPLETED',started_at=coalesce(started_at,now()),completed_at=coalesce(completed_at,now()),notes=coalesce($2,notes),updated_at=now() where service_order_id=$1::uuid and code='CONTRACT_PAYMENT'`,orderId,note);await tx.$executeRawUnsafe(`update service_order_steps set status='IN_PROGRESS',started_at=coalesce(started_at,now()),updated_at=now() where service_order_id=$1::uuid and code='INFORMATION_COLLECTION' and status='PENDING'`,orderId);const after=(await tx.$queryRawUnsafe<any[]>(`select id,payment_status,status,progress,metadata from service_orders where id=$1::uuid`,orderId))[0];return{already:false,before,after};});if(!result.already){const calc=await recalc(orderId);await cpAudit(req,'EXPERT_PAYMENT_CONFIRMED_MANUAL',orderId,result.before,{...result.after,...calc},{proofReference,note,financialMutation:false});}return res.json({success:true,data:{orderId,paymentStatus:'PAID',alreadyPaid:result.already,financialMutation:false}});}catch(e:any){if(e?.message==='NOT_FOUND')return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Contratação não encontrada.'}});console.error('[cp.expert.payment]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao confirmar pagamento.'}});}}
