import { Response } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import prisma from '../../../core/prisma';
import { ControlPlaneRequest } from '../middleware/control-plane-auth.middleware';
import { writeControlPlaneAudit } from '../services/control-plane-audit.service';

const text=(v:unknown,max=4000)=>String(v??'').trim().slice(0,max);
const uuid=(v:unknown)=>text(v,80)||null;
const bool=(v:unknown,f=false)=>v===undefined?f:v===true||String(v).toLowerCase()==='true';
const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const jsonObj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const providerFamily=(v:unknown)=>text(v,100).toLowerCase().split('-')[0].split('_')[0];
const redactVault=(row:any)=>({id:row.id,merchant_id:row.merchant_id,store_id:row.store_id,provider:row.provider,is_active:row.is_active,created_at:row.created_at,credentials_configured:Boolean(row.credentials&&Object.keys(typeof row.credentials==='object'?row.credentials:{}).length),credential_fields:row.credentials&&typeof row.credentials==='object'?Object.keys(row.credentials).sort():[]});

async function audit(req:ControlPlaneRequest,action:string,type:string,id:string|null,before?:unknown,after?:unknown,metadata?:Record<string,unknown>){
  await writeControlPlaneAudit({actorUserId:req.controlPlane?.userId||null,action,entityType:type,entityId:id,beforeData:before,afterData:after,metadata,req});
}
async function merchantExists(id:string){return (await prisma.$queryRawUnsafe<any[]>(`select id from merchants where id=$1::uuid`,id))[0];}
async function storeRow(id:string){return (await prisma.$queryRawUnsafe<any[]>(`select * from stores where id=$1::uuid`,id))[0];}
async function vaultRow(id:string){return (await prisma.$queryRawUnsafe<any[]>(`select * from gateway_vaults where id=$1::uuid`,id))[0];}
async function accountRow(id:string){return (await prisma.$queryRawUnsafe<any[]>(`select * from provider_accounts where id=$1::uuid`,id))[0];}
async function connectionRow(id:string){return (await prisma.$queryRawUnsafe<any[]>(`select * from provider_connections where id=$1::uuid`,id))[0];}

export async function createMerchant(req:ControlPlaneRequest,res:Response){
 try{
  const email=text(req.body?.email,320).toLowerCase(), name=text(req.body?.name,250);
  if(!email||!name) return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Email e nome são obrigatórios.'}});
  const password=text(req.body?.password,500); const generated=!password; const raw=password||crypto.randomBytes(32).toString('base64url');
  if(password&&password.length<12) return res.status(400).json({success:false,error:{code:'PASSWORD_POLICY',message:'Password deve ter pelo menos 12 caracteres.'}});
  const hash=await bcrypt.hash(raw,12);
  const tier=text(req.body?.tier||'TIER_C_STANDARD',80).toUpperCase();
  const tierOk=await prisma.$queryRawUnsafe<any[]>(`select code from platform_tiers where upper(code)=upper($1) and active=true limit 1`,tier);
  if(!tierOk[0]) return res.status(409).json({success:false,error:{code:'TIER_INVALID',message:'Tier inválido.'}});
  const rows=await prisma.$queryRawUnsafe<any[]>(`insert into merchants(email,name,company,tier,status,kyc_status,risk_score,password_hash) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,email,name,company,tier,status,kyc_status,risk_score,created_at`,email,name,text(req.body?.company,300)||null,tier,text(req.body?.status||'pending',40),text(req.body?.kycStatus||'not_submitted',60),Math.max(0,Math.min(100,Math.round(num(req.body?.riskScore,0)))),hash);
  await audit(req,'MERCHANT_CREATED','merchant',String(rows[0].id),undefined,rows[0],{passwordGenerated:generated,loginReady:!generated});
  return res.status(201).json({success:true,data:{merchant:rows[0],passwordGenerated:generated,passwordReturned:false}});
 }catch(e:any){if(String(e?.code)==='P2002'||String(e?.message||'').includes('merchants_email')) return res.status(409).json({success:false,error:{code:'EMAIL_EXISTS',message:'Email já registado.'}});console.error('[cp.merchant.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar Merchant.'}});}
}

export async function updateMerchant(req:ControlPlaneRequest,res:Response){
 try{
  const id=text(req.params.id,80); const before=(await prisma.$queryRawUnsafe<any[]>(`select id,email,name,company,tier,status,kyc_status,risk_score from merchants where id=$1::uuid`,id))[0];
  if(!before) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Merchant não encontrado.'}});
  const tier=req.body?.tier===undefined?before.tier:text(req.body.tier,80).toUpperCase();
  if(req.body?.tier!==undefined){const t=await prisma.$queryRawUnsafe<any[]>(`select code from platform_tiers where upper(code)=upper($1) and active=true`,tier);if(!t[0])return res.status(409).json({success:false,error:{code:'TIER_INVALID',message:'Tier inválido.'}});}
  const rows=await prisma.$queryRawUnsafe<any[]>(`update merchants set name=$2,company=$3,tier=$4,status=$5,kyc_status=$6,risk_score=$7,updated_at=now() where id=$1::uuid returning id,email,name,company,tier,status,kyc_status,risk_score,updated_at`,id,req.body?.name===undefined?before.name:text(req.body.name,250),req.body?.company===undefined?before.company:(text(req.body.company,300)||null),tier,req.body?.status===undefined?before.status:text(req.body.status,40),req.body?.kycStatus===undefined?before.kyc_status:text(req.body.kycStatus,60),req.body?.riskScore===undefined?before.risk_score:Math.max(0,Math.min(100,Math.round(num(req.body.riskScore,0)))));
  await audit(req,'MERCHANT_UPDATED','merchant',id,before,rows[0]); return res.json({success:true,data:{merchant:rows[0]}});
 }catch(e:any){console.error('[cp.merchant.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar Merchant.'}});}
}

export async function deleteMerchant(req:ControlPlaneRequest,res:Response){
 try{
  const id=text(req.params.id,80); const before=(await prisma.$queryRawUnsafe<any[]>(`select id,email,name,status from merchants where id=$1::uuid`,id))[0]; if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Merchant não encontrado.'}});
  const c=(await prisma.$queryRawUnsafe<any[]>(`select (select count(*)::int from transactions where merchant_id=$1::uuid) transactions,(select count(*)::int from wallet_movements where merchant_id=$1::uuid) movements,(select count(*)::int from payout_requests where merchant_id=$1::uuid and deleted_at is null) payouts,(select count(*)::int from stores where merchant_id=$1::uuid) stores,(select count(*)::int from wallets where merchant_id=$1::uuid) wallets,(select count(*)::int from service_orders where merchant_id=$1::uuid) expert_orders`,id))[0];
  const blocked=Object.values(c).some(v=>Number(v)>0); if(blocked){await prisma.$executeRawUnsafe(`update merchants set status='suspended',updated_at=now() where id=$1::uuid`,id);await audit(req,'MERCHANT_DELETE_BLOCKED_SUSPENDED','merchant',id,before,{status:'suspended'},{dependencies:c});return res.status(409).json({success:false,error:{code:'HAS_DEPENDENCIES',message:'Merchant possui histórico/dependências e foi suspenso em vez de apagado.'},data:{dependencies:c,suspended:true}});}
  await prisma.$executeRawUnsafe(`delete from merchants where id=$1::uuid`,id);await audit(req,'MERCHANT_DELETED','merchant',id,before);return res.json({success:true,data:{deleted:true,id}});
 }catch(e:any){console.error('[cp.merchant.delete]',e);return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar Merchant.'}});}
}

export async function createStore(req:ControlPlaneRequest,res:Response){
 try{
  const merchantId=text(req.body?.merchantId,80), code=text(req.body?.storeCode,100).toUpperCase(), name=text(req.body?.name,250);
  if(!merchantId||!code||!name)return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Merchant, código e nome são obrigatórios.'}}); if(!await merchantExists(merchantId))return res.status(404).json({success:false,error:{code:'MERCHANT_NOT_FOUND',message:'Merchant não encontrado.'}});
  const rows=await prisma.$queryRawUnsafe<any[]>(`insert into stores(merchant_id,store_code,name,domain,status,revenue,currency,routing_rules,logo_url,theme) values($1::uuid,$2,$3,$4,$5,0,$6,$7::jsonb,$8,$9) returning *`,merchantId,code,name,text(req.body?.domain,500)||null,text(req.body?.status||'draft',40),text(req.body?.currency||'EUR',20).toUpperCase(),JSON.stringify(jsonObj(req.body?.routingRules)),text(req.body?.logoUrl,1000)||null,text(req.body?.theme||'light',100));
  await audit(req,'STORE_CREATED','store',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{store:rows[0]}});
 }catch(e:any){if(String(e?.message||'').includes('store_code'))return res.status(409).json({success:false,error:{code:'STORE_CODE_EXISTS',message:'Código de Store já existe.'}});console.error('[cp.store.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar Store.'}});}
}
export async function updateStore(req:ControlPlaneRequest,res:Response){
 try{const id=text(req.params.id,80),before=await storeRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Store não encontrada.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update stores set name=$2,domain=$3,status=$4,currency=$5,routing_rules=$6::jsonb,logo_url=$7,theme=$8 where id=$1::uuid returning *`,id,req.body?.name===undefined?before.name:text(req.body.name,250),req.body?.domain===undefined?before.domain:(text(req.body.domain,500)||null),req.body?.status===undefined?before.status:text(req.body.status,40),req.body?.currency===undefined?before.currency:text(req.body.currency,20).toUpperCase(),JSON.stringify(req.body?.routingRules===undefined?(before.routing_rules||{}):jsonObj(req.body.routingRules)),req.body?.logoUrl===undefined?before.logo_url:(text(req.body.logoUrl,1000)||null),req.body?.theme===undefined?before.theme:text(req.body.theme,100));await audit(req,'STORE_UPDATED','store',id,before,rows[0]);return res.json({success:true,data:{store:rows[0]}});}catch(e:any){console.error('[cp.store.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar Store.'}});}}
export async function deleteStore(req:ControlPlaneRequest,res:Response){
 try{const id=text(req.params.id,80),before=await storeRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Store não encontrada.'}});const c=(await prisma.$queryRawUnsafe<any[]>(`select (select count(*)::int from transactions where store_id=$1::uuid) transactions,(select count(*)::int from payout_requests where store_id=$1::uuid and deleted_at is null) payouts,(select count(*)::int from provider_connections where store_id=$1::uuid) connections,(select count(*)::int from gateway_vaults where store_id=$1::uuid) vaults,(select count(*)::int from checkout_sessions where store_id=$1::uuid) checkout_sessions,(select count(*)::int from service_orders where target_store_id=$1::uuid) expert_links`,id))[0];if(Object.values(c).some(v=>Number(v)>0)){await prisma.$executeRawUnsafe(`update stores set status='inactive' where id=$1::uuid`,id);await audit(req,'STORE_DELETE_BLOCKED_DEACTIVATED','store',id,before,{status:'inactive'},{dependencies:c});return res.status(409).json({success:false,error:{code:'HAS_DEPENDENCIES',message:'Store possui histórico/dependências e foi desativada.'},data:{dependencies:c,deactivated:true}});}await prisma.$executeRawUnsafe(`delete from stores where id=$1::uuid`,id);await audit(req,'STORE_DELETED','store',id,before);return res.json({success:true,data:{deleted:true,id}});}catch(e:any){console.error('[cp.store.delete]',e);return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar Store.'}});}}

export async function listTiers(_req:ControlPlaneRequest,res:Response){try{const rows=await prisma.$queryRawUnsafe<any[]>(`select * from platform_tiers order by rank,code`);return res.json({success:true,data:{tiers:rows}});}catch(e){return res.status(500).json({success:false,error:{code:'READ_ERROR',message:'Falha ao carregar tiers.'}});}}
export async function createTier(req:ControlPlaneRequest,res:Response){try{const code=text(req.body?.code,80).toUpperCase(),name=text(req.body?.name,200);if(!code||!name)return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Código e nome obrigatórios.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`insert into platform_tiers(code,name,description,rank,active,fee_basis,default_fee_percent_bps,default_fee_fixed_minor,min_fee_minor,max_fee_minor,limits,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb) returning *`,code,name,text(req.body?.description,1000)||null,Math.round(num(req.body?.rank,100)),bool(req.body?.active,true),text(req.body?.feeBasis||'SETTLEMENT_GROSS',80),Math.max(0,Math.round(num(req.body?.feePercentBps,0))),Math.max(0,Math.round(num(req.body?.feeFixedMinor,0))),req.body?.minFeeMinor==null?null:Math.max(0,Math.round(num(req.body.minFeeMinor))),req.body?.maxFeeMinor==null?null:Math.max(0,Math.round(num(req.body.maxFeeMinor))),JSON.stringify(jsonObj(req.body?.limits)),JSON.stringify(jsonObj(req.body?.metadata)));await audit(req,'TIER_CREATED','platform_tier',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{tier:rows[0]}});}catch(e:any){if(String(e?.message||'').includes('platform_tiers_code_uq'))return res.status(409).json({success:false,error:{code:'CODE_EXISTS',message:'Tier já existe.'}});return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar tier.'}});}}
export async function updateTier(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=(await prisma.$queryRawUnsafe<any[]>(`select * from platform_tiers where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Tier não encontrado.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update platform_tiers set name=$2,description=$3,rank=$4,active=$5,fee_basis=$6,default_fee_percent_bps=$7,default_fee_fixed_minor=$8,min_fee_minor=$9,max_fee_minor=$10,limits=$11::jsonb,metadata=$12::jsonb where id=$1::uuid returning *`,id,req.body?.name===undefined?before.name:text(req.body.name,200),req.body?.description===undefined?before.description:(text(req.body.description,1000)||null),req.body?.rank===undefined?before.rank:Math.round(num(req.body.rank)),req.body?.active===undefined?before.active:bool(req.body.active),req.body?.feeBasis===undefined?before.fee_basis:text(req.body.feeBasis,80),req.body?.feePercentBps===undefined?before.default_fee_percent_bps:Math.max(0,Math.round(num(req.body.feePercentBps))),req.body?.feeFixedMinor===undefined?before.default_fee_fixed_minor:Math.max(0,Math.round(num(req.body.feeFixedMinor))),req.body?.minFeeMinor===undefined?before.min_fee_minor:(req.body.minFeeMinor==null?null:Math.max(0,Math.round(num(req.body.minFeeMinor)))),req.body?.maxFeeMinor===undefined?before.max_fee_minor:(req.body.maxFeeMinor==null?null:Math.max(0,Math.round(num(req.body.maxFeeMinor)))),JSON.stringify(req.body?.limits===undefined?(before.limits||{}):jsonObj(req.body.limits)),JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):jsonObj(req.body.metadata)));await audit(req,'TIER_UPDATED','platform_tier',id,before,rows[0]);return res.json({success:true,data:{tier:rows[0]}});}catch(e){return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar tier.'}});}}
export async function deleteTier(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=(await prisma.$queryRawUnsafe<any[]>(`select * from platform_tiers where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Tier não encontrado.'}});const c=(await prisma.$queryRawUnsafe<any[]>(`select count(*)::int c from merchants where upper(tier)=upper($1)`,String(before.code)))[0];if(Number(c.c)>0){await prisma.$executeRawUnsafe(`update platform_tiers set active=false where id=$1::uuid`,id);await audit(req,'TIER_DELETE_BLOCKED_DEACTIVATED','platform_tier',id,before,{...before,active:false},{merchantCount:Number(c.c)});return res.status(409).json({success:false,error:{code:'IN_USE',message:'Tier está em uso e foi desativado.'},data:{deactivated:true,merchantCount:Number(c.c)}});}await prisma.$executeRawUnsafe(`delete from platform_tiers where id=$1::uuid`,id);await audit(req,'TIER_DELETED','platform_tier',id,before);return res.json({success:true,data:{deleted:true,id}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar tier.'}});}}

export async function createFee(req:ControlPlaneRequest,res:Response){try{const merchantId=text(req.body?.merchantId,80),storeId=text(req.body?.storeId,80);const s=await storeRow(storeId);if(!s||String(s.merchant_id)!==merchantId)return res.status(409).json({success:false,error:{code:'STORE_MERCHANT_MISMATCH',message:'Store/Merchant inválidos.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`insert into store_fee_configs(merchant_id,store_id,fee_basis,fee_percent_bps,fee_fixed_minor,min_fee_minor,max_fee_minor,active,effective_from,effective_to,metadata) values($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9::timestamptz,$10::timestamptz,$11::jsonb) returning *`,merchantId,storeId,text(req.body?.feeBasis||'SETTLEMENT_GROSS',80),Math.max(0,Math.round(num(req.body?.feePercentBps))),Math.max(0,Math.round(num(req.body?.feeFixedMinor))),req.body?.minFeeMinor==null?null:Math.max(0,Math.round(num(req.body.minFeeMinor))),req.body?.maxFeeMinor==null?null:Math.max(0,Math.round(num(req.body.maxFeeMinor))),bool(req.body?.active,true),text(req.body?.effectiveFrom||new Date().toISOString(),80),uuid(req.body?.effectiveTo),JSON.stringify(jsonObj(req.body?.metadata)));await audit(req,'FEE_CONFIG_CREATED','store_fee_config',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{feeConfig:rows[0]}});}catch(e:any){console.error('[cp.fee.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar fee.'}});}}
export async function updateFee(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=(await prisma.$queryRawUnsafe<any[]>(`select * from store_fee_configs where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Fee não encontrada.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update store_fee_configs set fee_basis=$2,fee_percent_bps=$3,fee_fixed_minor=$4,min_fee_minor=$5,max_fee_minor=$6,active=$7,effective_from=$8::timestamptz,effective_to=$9::timestamptz,metadata=$10::jsonb,updated_at=now() where id=$1::uuid returning *`,id,req.body?.feeBasis===undefined?before.fee_basis:text(req.body.feeBasis,80),req.body?.feePercentBps===undefined?before.fee_percent_bps:Math.max(0,Math.round(num(req.body.feePercentBps))),req.body?.feeFixedMinor===undefined?before.fee_fixed_minor:Math.max(0,Math.round(num(req.body.feeFixedMinor))),req.body?.minFeeMinor===undefined?before.min_fee_minor:(req.body.minFeeMinor==null?null:Math.max(0,Math.round(num(req.body.minFeeMinor)))),req.body?.maxFeeMinor===undefined?before.max_fee_minor:(req.body.maxFeeMinor==null?null:Math.max(0,Math.round(num(req.body.maxFeeMinor)))),req.body?.active===undefined?before.active:bool(req.body.active),req.body?.effectiveFrom===undefined?before.effective_from:text(req.body.effectiveFrom,80),req.body?.effectiveTo===undefined?before.effective_to:(req.body.effectiveTo?text(req.body.effectiveTo,80):null),JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):jsonObj(req.body.metadata)));await audit(req,'FEE_CONFIG_UPDATED','store_fee_config',id,before,rows[0]);return res.json({success:true,data:{feeConfig:rows[0]}});}catch(e:any){console.error('[cp.fee.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar fee.'}});}}
export async function deleteFee(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=(await prisma.$queryRawUnsafe<any[]>(`select * from store_fee_configs where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Fee não encontrada.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update store_fee_configs set active=false,effective_to=coalesce(effective_to,now()),updated_at=now() where id=$1::uuid returning *`,id);await audit(req,'FEE_CONFIG_DEACTIVATED','store_fee_config',id,before,rows[0]);return res.json({success:true,data:{deactivated:true,feeConfig:rows[0]}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao desativar fee.'}});}}

export async function createProviderAccount(req:ControlPlaneRequest,res:Response){try{const provider=text(req.body?.provider,100),external=text(req.body?.externalAccountId,250);if(!provider||!external)return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Provider e externalAccountId obrigatórios.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`insert into provider_accounts(provider,external_account_id,environment,country,default_currency,status,metadata) values($1,$2,$3,$4,$5,$6,$7::jsonb) returning *`,provider,external,text(req.body?.environment||'test',30),text(req.body?.country,10)||null,text(req.body?.defaultCurrency,20).toUpperCase()||null,text(req.body?.status||'active',40),JSON.stringify(jsonObj(req.body?.metadata)));await audit(req,'PROVIDER_ACCOUNT_CREATED','provider_account',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{providerAccount:rows[0]}});}catch(e:any){console.error('[cp.pa.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar Provider Account.'}});}}
export async function updateProviderAccount(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await accountRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Provider Account não encontrado.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update provider_accounts set provider=$2,external_account_id=$3,environment=$4,country=$5,default_currency=$6,status=$7,metadata=$8::jsonb,updated_at=now() where id=$1::uuid returning *`,id,req.body?.provider===undefined?before.provider:text(req.body.provider,100),req.body?.externalAccountId===undefined?before.external_account_id:text(req.body.externalAccountId,250),req.body?.environment===undefined?before.environment:text(req.body.environment,30),req.body?.country===undefined?before.country:(text(req.body.country,10)||null),req.body?.defaultCurrency===undefined?before.default_currency:(text(req.body.defaultCurrency,20).toUpperCase()||null),req.body?.status===undefined?before.status:text(req.body.status,40),JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):jsonObj(req.body.metadata)));await audit(req,'PROVIDER_ACCOUNT_UPDATED','provider_account',id,before,rows[0]);return res.json({success:true,data:{providerAccount:rows[0]}});}catch(e){return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar Provider Account.'}});}}
export async function deleteProviderAccount(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await accountRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Provider Account não encontrado.'}});const c=Number((await prisma.$queryRawUnsafe<any[]>(`select count(*)::int c from provider_connections where provider_account_id=$1::uuid`,id))[0].c);if(c>0)return res.status(409).json({success:false,error:{code:'IN_USE',message:'Provider Account possui connections e não pode ser apagado.'},data:{connections:c}});await prisma.$executeRawUnsafe(`delete from provider_accounts where id=$1::uuid`,id);await audit(req,'PROVIDER_ACCOUNT_DELETED','provider_account',id,before);return res.json({success:true,data:{deleted:true,id}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar Provider Account.'}});}}

export async function createVault(req:ControlPlaneRequest,res:Response){try{const merchantId=text(req.body?.merchantId,80),storeId=uuid(req.body?.storeId),provider=text(req.body?.provider,120),credentials=jsonObj(req.body?.credentials);if(!merchantId||!provider||Object.keys(credentials).length===0)return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Merchant, provider e credentials são obrigatórios.'}});if(!await merchantExists(merchantId))return res.status(404).json({success:false,error:{code:'MERCHANT_NOT_FOUND',message:'Merchant não encontrado.'}});if(storeId){const s=await storeRow(storeId);if(!s||String(s.merchant_id)!==merchantId)return res.status(409).json({success:false,error:{code:'STORE_MERCHANT_MISMATCH',message:'Store não pertence ao Merchant.'}});}const rows=await prisma.$queryRawUnsafe<any[]>(`insert into gateway_vaults(merchant_id,store_id,provider,credentials,is_active) values($1::uuid,$2::uuid,$3,$4::jsonb,$5) returning *`,merchantId,storeId,provider,JSON.stringify(credentials),bool(req.body?.isActive,true));await audit(req,'GATEWAY_VAULT_CREATED','gateway_vault',String(rows[0].id),undefined,redactVault(rows[0]),{credentialsWritten:true});return res.status(201).json({success:true,data:{gatewayVault:redactVault(rows[0])}});}catch(e:any){console.error('[cp.vault.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar Gateway Vault.'}});}}
export async function updateVault(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await vaultRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Gateway Vault não encontrado.'}});const storeId=req.body?.storeId===undefined?before.store_id:uuid(req.body.storeId);if(storeId){const s=await storeRow(String(storeId));if(!s||String(s.merchant_id)!==String(before.merchant_id))return res.status(409).json({success:false,error:{code:'STORE_MERCHANT_MISMATCH',message:'Store não pertence ao Merchant do Vault.'}});}const credentials=req.body?.credentials===undefined?before.credentials:jsonObj(req.body.credentials);if(req.body?.credentials!==undefined&&Object.keys(credentials).length===0)return res.status(400).json({success:false,error:{code:'EMPTY_CREDENTIALS',message:'Credentials não podem ser vazias.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update gateway_vaults set store_id=$2::uuid,provider=$3,credentials=$4::jsonb,is_active=$5 where id=$1::uuid returning *`,id,storeId,req.body?.provider===undefined?before.provider:text(req.body.provider,120),JSON.stringify(credentials),req.body?.isActive===undefined?before.is_active:bool(req.body.isActive));await audit(req,'GATEWAY_VAULT_UPDATED','gateway_vault',id,redactVault(before),redactVault(rows[0]),{credentialsWritten:req.body?.credentials!==undefined});return res.json({success:true,data:{gatewayVault:redactVault(rows[0])}});}catch(e:any){console.error('[cp.vault.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar Gateway Vault.'}});}}
export async function deleteVault(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await vaultRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Gateway Vault não encontrado.'}});const c=(await prisma.$queryRawUnsafe<any[]>(`select (select count(*)::int from provider_connections where gateway_vault_id=$1::uuid) connections,(select count(*)::int from transactions where gateway_vault_id=$1::uuid) transactions,(select count(*)::int from checkout_sessions where gateway_vault_id=$1::uuid) checkout_sessions`,id))[0];if(Object.values(c).some(v=>Number(v)>0)){await prisma.$executeRawUnsafe(`update gateway_vaults set is_active=false where id=$1::uuid`,id);await audit(req,'GATEWAY_VAULT_DELETE_BLOCKED_DEACTIVATED','gateway_vault',id,redactVault(before),{...redactVault(before),is_active:false},{dependencies:c});return res.status(409).json({success:false,error:{code:'IN_USE',message:'Vault possui dependências e foi desativado.'},data:{deactivated:true,dependencies:c}});}await prisma.$executeRawUnsafe(`delete from gateway_vaults where id=$1::uuid`,id);await audit(req,'GATEWAY_VAULT_DELETED','gateway_vault',id,redactVault(before));return res.json({success:true,data:{deleted:true,id}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar Vault.'}});}}

async function validateConnection(providerAccountId:string,merchantId:string,storeId:string,gatewayVaultId:string|null){const [pa,s,v]=await Promise.all([accountRow(providerAccountId),storeRow(storeId),gatewayVaultId?vaultRow(gatewayVaultId):Promise.resolve(null)]);if(!pa)throw new Error('PROVIDER_ACCOUNT_NOT_FOUND');if(!s||String(s.merchant_id)!==merchantId)throw new Error('STORE_MERCHANT_MISMATCH');if(v){if(String(v.merchant_id)!==merchantId)throw new Error('VAULT_MERCHANT_MISMATCH');if(v.store_id&&String(v.store_id)!==storeId)throw new Error('VAULT_STORE_MISMATCH');if(providerFamily(v.provider)!==providerFamily(pa.provider))throw new Error('PROVIDER_MISMATCH');}return{pa,s,v};}
const connectionErrors:Record<string,string>={PROVIDER_ACCOUNT_NOT_FOUND:'Provider Account não encontrado.',STORE_MERCHANT_MISMATCH:'Store não pertence ao Merchant.',VAULT_MERCHANT_MISMATCH:'Vault não pertence ao Merchant.',VAULT_STORE_MISMATCH:'Vault está ligado a outra Store.',PROVIDER_MISMATCH:'Provider Account e Gateway Vault são de providers diferentes.'};
export async function createConnection(req:ControlPlaneRequest,res:Response){try{const providerAccountId=text(req.body?.providerAccountId,80),merchantId=text(req.body?.merchantId,80),storeId=text(req.body?.storeId,80),gatewayVaultId=uuid(req.body?.gatewayVaultId);await validateConnection(providerAccountId,merchantId,storeId,gatewayVaultId);const rows=await prisma.$queryRawUnsafe<any[]>(`insert into provider_connections(provider_account_id,merchant_id,store_id,gateway_vault_id,alias,mode,credential_mode,capture_policy,status,shadow_mode,ledger_enabled,metadata) values($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) returning *`,providerAccountId,merchantId,storeId,gatewayVaultId,text(req.body?.alias||'connection',160),text(req.body?.mode||'DIRECT',80),text(req.body?.credentialMode||'VAULT',80),text(req.body?.capturePolicy||'automatic',80),text(req.body?.status||'active',40),bool(req.body?.shadowMode,false),bool(req.body?.ledgerEnabled,true),JSON.stringify(jsonObj(req.body?.metadata)));await audit(req,'PROVIDER_CONNECTION_CREATED','provider_connection',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{providerConnection:rows[0]}});}catch(e:any){if(connectionErrors[e?.message])return res.status(409).json({success:false,error:{code:e.message,message:connectionErrors[e.message]}});console.error('[cp.connection.create]',e);return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar Provider Connection.'}});}}
export async function updateConnection(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await connectionRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Provider Connection não encontrada.'}});const providerAccountId=req.body?.providerAccountId===undefined?String(before.provider_account_id):text(req.body.providerAccountId,80),merchantId=String(before.merchant_id),storeId=req.body?.storeId===undefined?String(before.store_id):text(req.body.storeId,80),gatewayVaultId=req.body?.gatewayVaultId===undefined?(before.gateway_vault_id?String(before.gateway_vault_id):null):uuid(req.body.gatewayVaultId);await validateConnection(providerAccountId,merchantId,storeId,gatewayVaultId);const rows=await prisma.$queryRawUnsafe<any[]>(`update provider_connections set provider_account_id=$2::uuid,store_id=$3::uuid,gateway_vault_id=$4::uuid,alias=$5,mode=$6,credential_mode=$7,capture_policy=$8,status=$9,shadow_mode=$10,ledger_enabled=$11,metadata=$12::jsonb,updated_at=now() where id=$1::uuid returning *`,id,providerAccountId,storeId,gatewayVaultId,req.body?.alias===undefined?before.alias:text(req.body.alias,160),req.body?.mode===undefined?before.mode:text(req.body.mode,80),req.body?.credentialMode===undefined?before.credential_mode:text(req.body.credentialMode,80),req.body?.capturePolicy===undefined?before.capture_policy:text(req.body.capturePolicy,80),req.body?.status===undefined?before.status:text(req.body.status,40),req.body?.shadowMode===undefined?before.shadow_mode:bool(req.body.shadowMode),req.body?.ledgerEnabled===undefined?before.ledger_enabled:bool(req.body.ledgerEnabled),JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):jsonObj(req.body.metadata)));await audit(req,'PROVIDER_CONNECTION_UPDATED','provider_connection',id,before,rows[0]);return res.json({success:true,data:{providerConnection:rows[0]}});}catch(e:any){if(connectionErrors[e?.message])return res.status(409).json({success:false,error:{code:e.message,message:connectionErrors[e.message]}});console.error('[cp.connection.update]',e);return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar Provider Connection.'}});}}
export async function deleteConnection(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=await connectionRow(id);if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Connection não encontrada.'}});const c=(await prisma.$queryRawUnsafe<any[]>(`select (select count(*)::int from store_processing_profiles where provider_connection_id=$1::uuid) profiles,(select count(*)::int from transactions where provider_connection_id=$1::uuid) transactions`,id))[0];if(Object.values(c).some(v=>Number(v)>0)){const rows=await prisma.$queryRawUnsafe<any[]>(`update provider_connections set status='inactive',ledger_enabled=false,updated_at=now() where id=$1::uuid returning *`,id);await audit(req,'PROVIDER_CONNECTION_DELETE_BLOCKED_DEACTIVATED','provider_connection',id,before,rows[0],{dependencies:c});return res.status(409).json({success:false,error:{code:'IN_USE',message:'Connection possui dependências e foi desativada.'},data:{deactivated:true,dependencies:c}});}await prisma.$executeRawUnsafe(`delete from provider_connections where id=$1::uuid`,id);await audit(req,'PROVIDER_CONNECTION_DELETED','provider_connection',id,before);return res.json({success:true,data:{deleted:true,id}});}catch(e:any){console.error('[cp.connection.delete]',e);return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao apagar Connection.'}});}}

export async function upsertProcessingProfile(req:ControlPlaneRequest,res:Response){try{const storeId=text(req.params.storeId,80),s=await storeRow(storeId);if(!s)return res.status(404).json({success:false,error:{code:'STORE_NOT_FOUND',message:'Store não encontrada.'}});const connectionId=uuid(req.body?.providerConnectionId);if(connectionId){const c=await connectionRow(connectionId);if(!c||String(c.store_id)!==storeId||String(c.merchant_id)!==String(s.merchant_id))return res.status(409).json({success:false,error:{code:'CONNECTION_STORE_MISMATCH',message:'Connection não pertence à Store.'}});}const before=(await prisma.$queryRawUnsafe<any[]>(`select * from store_processing_profiles where store_id=$1::uuid order by updated_at desc limit 1`,storeId))[0];let rows;if(before){rows=await prisma.$queryRawUnsafe<any[]>(`update store_processing_profiles set runtime_generation=$2,processing_mode=$3,activation_state=$4,provider_connection_id=$5::uuid,effective_from=$6::timestamptz,legacy_compatibility=$7,metadata=$8::jsonb,updated_at=now() where id=$1::uuid returning *`,String(before.id),text(req.body?.runtimeGeneration||before.runtime_generation,80),req.body?.processingMode===undefined?before.processing_mode:(text(req.body.processingMode,80)||null),text(req.body?.activationState||before.activation_state,80),connectionId,req.body?.effectiveFrom?text(req.body.effectiveFrom,80):(before.effective_from||new Date().toISOString()),req.body?.legacyCompatibility===undefined?before.legacy_compatibility:bool(req.body.legacyCompatibility),JSON.stringify(req.body?.metadata===undefined?(before.metadata||{}):jsonObj(req.body.metadata)));}else{rows=await prisma.$queryRawUnsafe<any[]>(`insert into store_processing_profiles(merchant_id,store_id,runtime_generation,processing_mode,activation_state,provider_connection_id,effective_from,legacy_compatibility,metadata) values($1::uuid,$2::uuid,$3,$4,$5,$6::uuid,$7::timestamptz,$8,$9::jsonb) returning *`,String(s.merchant_id),storeId,text(req.body?.runtimeGeneration||'V1',80),text(req.body?.processingMode,80)||null,text(req.body?.activationState||'ACTIVE',80),connectionId,text(req.body?.effectiveFrom||new Date().toISOString(),80),bool(req.body?.legacyCompatibility,false),JSON.stringify(jsonObj(req.body?.metadata)));}await audit(req,before?'PROCESSING_PROFILE_UPDATED':'PROCESSING_PROFILE_CREATED','store_processing_profile',String(rows[0].id),before,rows[0]);return res.json({success:true,data:{processingProfile:rows[0]}});}catch(e:any){console.error('[cp.profile.upsert]',e);return res.status(500).json({success:false,error:{code:'UPSERT_ERROR',message:'Falha ao configurar processing profile.'}});}}

const ROLES=new Set(['SUPER_ADMIN','OPERATIONS','FINANCE','RISK','SUPPORT','EXPERT_OPS','READ_ONLY']);
export async function createInternalUser(req:ControlPlaneRequest,res:Response){try{const email=text(req.body?.email,320).toLowerCase(),name=text(req.body?.name,250),password=text(req.body?.password,500),role=text(req.body?.role||'READ_ONLY',50).toUpperCase();if(!email||!name||password.length<12)return res.status(400).json({success:false,error:{code:'REQUIRED',message:'Email, nome e password (12+) são obrigatórios.'}});if(!ROLES.has(role))return res.status(400).json({success:false,error:{code:'ROLE_INVALID',message:'Role inválido.'}});const hash=await bcrypt.hash(password,12);const rows=await prisma.$queryRawUnsafe<any[]>(`insert into control_plane_users(email,name,password_hash,role,permissions,status) values($1,$2,$3,$4,$5::jsonb,$6) returning id,email,name,role,permissions,status,created_at`,email,name,hash,role,JSON.stringify(jsonObj(req.body?.permissions)),text(req.body?.status||'active',30));await audit(req,'CONTROL_PLANE_USER_CREATED','control_plane_user',String(rows[0].id),undefined,rows[0]);return res.status(201).json({success:true,data:{user:rows[0]}});}catch(e:any){if(String(e?.message||'').includes('control_plane_users_email'))return res.status(409).json({success:false,error:{code:'EMAIL_EXISTS',message:'Utilizador já existe.'}});return res.status(500).json({success:false,error:{code:'CREATE_ERROR',message:'Falha ao criar utilizador.'}});}}
export async function updateInternalUser(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80),before=(await prisma.$queryRawUnsafe<any[]>(`select id,email,name,role,permissions,status from control_plane_users where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Utilizador não encontrado.'}});const role=req.body?.role===undefined?before.role:text(req.body.role,50).toUpperCase();if(!ROLES.has(role))return res.status(400).json({success:false,error:{code:'ROLE_INVALID',message:'Role inválido.'}});const rows=await prisma.$queryRawUnsafe<any[]>(`update control_plane_users set name=$2,role=$3,permissions=$4::jsonb,status=$5,updated_at=now() where id=$1::uuid returning id,email,name,role,permissions,status,updated_at`,id,req.body?.name===undefined?before.name:text(req.body.name,250),role,JSON.stringify(req.body?.permissions===undefined?(before.permissions||{}):jsonObj(req.body.permissions)),req.body?.status===undefined?before.status:text(req.body.status,30));if(req.body?.password!==undefined){const p=text(req.body.password,500);if(p.length<12)return res.status(400).json({success:false,error:{code:'PASSWORD_POLICY',message:'Password deve ter 12+ caracteres.'}});await prisma.$executeRawUnsafe(`update control_plane_users set password_hash=$2,updated_at=now() where id=$1::uuid`,id,await bcrypt.hash(p,12));await prisma.$executeRawUnsafe(`update control_plane_sessions set revoked_at=now() where user_id=$1::uuid and revoked_at is null`,id);}await audit(req,'CONTROL_PLANE_USER_UPDATED','control_plane_user',id,before,rows[0],{passwordReset:req.body?.password!==undefined});return res.json({success:true,data:{user:rows[0]}});}catch(e){return res.status(500).json({success:false,error:{code:'UPDATE_ERROR',message:'Falha ao atualizar utilizador.'}});}}
export async function deleteInternalUser(req:ControlPlaneRequest,res:Response){try{const id=text(req.params.id,80);if(id===req.controlPlane?.userId)return res.status(409).json({success:false,error:{code:'SELF_DELETE',message:'Não pode desativar a própria conta.'}});const before=(await prisma.$queryRawUnsafe<any[]>(`select id,email,name,role,status from control_plane_users where id=$1::uuid`,id))[0];if(!before)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Utilizador não encontrado.'}});await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`update control_plane_sessions set revoked_at=now() where user_id=$1::uuid and revoked_at is null`,id);await tx.$executeRawUnsafe(`update control_plane_users set status='disabled',updated_at=now() where id=$1::uuid`,id);});await audit(req,'CONTROL_PLANE_USER_DISABLED','control_plane_user',id,before,{...before,status:'disabled'});return res.json({success:true,data:{disabled:true,id}});}catch(e){return res.status(500).json({success:false,error:{code:'DELETE_ERROR',message:'Falha ao desativar utilizador.'}});}}
